---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "payment-postgres-secrets"
  labels:
    app.kubernetes.io/name: "PaymentsLedger"
    app.kubernetes.io/component: "payment-postgres"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.payment_postgres.payment_postgres_password }}"
type: "Opaque"
